kind: pipeline
type: docker
name: test

steps:
- name: build
  image: ashael/openmpi
  commands:
  - mpicc /drone/src/ring.c -o /drone/src/ring
- name: test
  image: ashael/openmpi
  commands:
  - mpirun -np 5 /drone/src/ring