kind: pipeline
type: docker
name: test

steps:
- name: build
  image: gcc:4.9
  commands:
  - cd /drone/src
  - gcc cli.c -o cli -lcrypto -lm
- name: test
  image: gcc:4.9
  commands:
  - cd /drone/src 
  # should exit non-zero and fail pipeline if either of these don't find a match
  - ./cli -bl -c 4 -p $(echo -n 'test1' | sha256sum) --verbose
  - ./cli -d dictionary_files/100_pass.txt -p $(echo -n '123456' | sha256sum)
